Library/authorization/urls.py
from django.urls import path

from .views import login_view, logout_view


app_name = 'authorization'
urlpatterns = [
    path('', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

Library/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('registration/', include('registration.urls')),
    path('authorization/', include('authorization.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library/library/urls.py
from django.urls import path

from .views import main, books, authors, feedback, certain_book, certain_author

app_name = 'library'
urlpatterns = [
    path('', main, name='main'),
    path('books/', books, name='books'),
    path('books/<int:book_id>', certain_book, name='certain_book'),
    path('authors/', authors, name='authors'),
    path('authors/<int:author_id>', certain_author, name='certain_author'),
    path('feedback/', feedback, name='feedback'),
]

Library/registration/urls.py
from django.urls import path

from . views import registration


app_name = 'registration'
urlpatterns = [
    path('', registration, name='registration'),
]

Library/authorization/models.py
from django.db import models

# Create your models here.

Library/library/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    photo = models.ImageField(upload_to='authors', default=None)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    bio = models.TextField()

    def __str__(self):
        return self.surname


class Book(models.Model):
    title = models.CharField(max_length=150)
    poster = models.ImageField(upload_to='posters')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    DIFFICULTIES = [
        ('L', 'Low'),
        ('M', 'Medium'),
        ('H', 'Hard'),
    ]
    difficulty = models.CharField(max_length=20, choices=DIFFICULTIES, default='L')
    LANGUAGES = [
        ('EN', 'English'),
        ('RU', 'Russian'),
    ]
    TECHNOLOGIES = [
        ('C++', 'C_Plus_Plus'),
        ('Python', 'Python'),
        ('JS', 'JavaScript'),
        ('Java', 'Java'),
        ('Others', 'Others'),
    ]
    technology = models.CharField(max_length=30, choices=TECHNOLOGIES, default='Others')
    language = models.CharField(max_length=20, choices=LANGUAGES, default='EN')
    content = models.TextField(default=None)
    score = models.FloatField()
    main_file = models.FileField(upload_to='books', default=None)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment_body = models.CharField(max_length=255)
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user_name.username


class Feedback(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    feed = models.TextField()

    def __str__(self):
        return self.name

Library/authorization/views.py
from django.shortcuts import render, redirect
from .services import authenticate_and_login_user, logout


def logout_view(request):
    logout(request)
    return redirect('library:main')


def login_view(request):
    if request.method == 'POST':
        message, context = authenticate_and_login_user(request)
        if message:
            return redirect('library:main')
        else:
            return render(request, 'authorization/authentication.html', context)
    else:
        return render(request, 'authorization/authentication.html')

Library/library/views.py
from django.shortcuts import render

from .services import get_user_and_form_context, get_user_books_and_form_context_with_filter, \
    get_user_book_and_form_context, get_user_authors_and_form_context, get_user_author_and_form_context, \
    get_user_and_send_feedback


def main(request):
    return render(request, 'library/index.html', get_user_and_form_context(request))


def books(request):
    return render(request, 'library/books.html', get_user_books_and_form_context_with_filter(request))


def certain_book(request, book_id):
    return render(request, 'library/detail_book.html', get_user_book_and_form_context(request, book_id))


def authors(request):
    return render(request, 'library/authors.html', get_user_authors_and_form_context(request))


def certain_author(request, author_id):
    return render(request, 'library/detail_author.html', get_user_author_and_form_context(request, author_id))


def feedback(request):
    return render(request, 'library/feedback.html', get_user_and_send_feedback(request))

Library/authorization/templates/authorization/authentication.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    <div class="content">
      <div class="registration_form">
        <form method="post">
          {% csrf_token %}
          <p>Введите ваше имя пользователя:</p>
          <input type="text" name="username" value="{{ valid_username }}">
          <p>Введите ваш пароль:</p>
          <input type="password" name="password" value="{{ valid_password }}"><br>
          <input type="submit" value="Вход">
          {% if login_error %}
            <div class="error">
                {{ login_error }}
            </div>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Library/authorization/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="{% static 'CSS/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
</head>
<body>
  <header>
    <div class="header">
      <div class="container">
        <div class="header_content-inner">
          <img class="header_logo" src="{% static 'CSS/logo.png' %}" href="index.html">
          <nav class="menu">
            <ul>
              <li><a href="{% url 'library:main' %}">Главная</a></li>
              <li><a href="{% url 'library:books' %}">Библиотека</a></li>
              <li><a href="{% url 'library:authors' %}">Авторы</a></li>
              <li><a href="{% url 'library:feedback' %}">Обратная связь</a></li>
              {% if User.username %}
                <li><a href="{% url 'authorization:logout' %}">Выход</a></li>
              {% else %}
                <li><a href="{% url 'authorization:login' %}">Вход</a></li>
                <li><a href="{% url 'registration:registration' %}">Регистрация</a></li>
              {% endif %}
            </ul>
        </div>
      </div>
    </div>
  </header>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
</body>
</html>

Library/library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="{% static 'CSS/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
</head>
<body>
  <header>
    <div class="header">
      <div class="container">
        <div class="header_content-inner">
          <img class="header_logo" src="{% static 'CSS/logo.png' %}" href="index.html">
          {% if User.username %}
          <p>Добро пожаловать, {{ User.username }} </p>
          {% endif %}
          <nav class="menu">
            <ul>
              <li><a href="{% url 'library:main' %}">Главная</a></li>
              <li><a href="{% url 'library:books' %}">Библиотека</a></li>
              <li><a href="{% url 'library:authors' %}">Авторы</a></li>
              <li><a href="{% url 'library:feedback' %}">Обратная связь</a></li>
              {% if User.username %}
                <li><a href="{% url 'authorization:logout' %}">Выход</a></li>
              {% else %}
                <li><a href="{% url 'authorization:login' %}">Вход</a></li>
                <li><a href="{% url 'registration:registration' %}">Регистрация</a></li>
              {% endif %}
            </ul>
        </div>
      </div>
    </div>
  </header>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
</body>
</html>

Library/library/templates/library/authors.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
  <div class="authors_stack">
    <h1> Список авторов, книги которых присутствуют на сайте:</h1>
    {% for author in Authors %}
    <div class="authors">
      <a href="/authors/{{ author.id }}">
        <img height="320px" width="200px" src="{{ author.photo.url }}">
        <center><p> {{ author.name }} {{ author.surname }}</p> </center>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

Library/library/templates/library/books.html
{% extends 'base.html' %}
{% block content %}
<div class="filter_content">
        <div class="filter">
          <form method="get">
            <ul>
              <li><p>Язык программирования:</p></li>
              <li><input type="checkbox" name="technology" value="Python">Python</li>
              <li><input type="checkbox" name="technology" value="Java">Java</li>
              <li><input type="checkbox" name="technology" value="C++">C++</li>
              <li><input type="checkbox" name="technology" value="JS">JavaScript  </li>
              <li><input type="checkbox" name="technology" value="Others">Остальные  </li>
              <li><p>Сложность:</p></li>
              <li><input type="checkbox" name="difficulty" value="L">Для новичков</li>
              <li><input type="checkbox" name="difficulty" value="M">Для опытных</li>
              <li><input type="checkbox" name="difficulty" value="H">Для профессионалов</li>
              <li><p>Язык:</p></li>
              <li><input type="checkbox" name="language" value="RU">Русский</li>
              <li><input type="checkbox" name="language" value="EN">Английский</li>
              <li class="submit_button"><input type="submit" name="submit" value="Применить"></li>
            </ul>
          </form>
        </div>
        <div class="content">
          <center><h1> Список книг:</h1></center>
          <div class="stack">
            {% for book in Books %}
            <div class="book">
              <a href="/books/{{ book.id }}">
                <img height="320px" width="200px" src="{{ book.poster.url }}">
                <center><p> {{ book.title }}</p> </center>
              </a>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
{% endblock %}

Library/library/templates/library/detail_author.html
{% extends 'base.html' %}
{% block content %}
      <div class="content">
        <div class="author_name_surname">
          <h2> {{ Author.name }} {{ Author.surname }} </h2>
        </div>
        <div class="certain_author">
            <div class="author_photo">
              <img height="320px" width="200px" src="{{ Author.photo.url }}">
            </div>
            <div class="author_bio">
              <h4> Биография: </h4>
              <p>
                {{ Author.bio }}
              </p>
            </div>
        </div>
      </div>
{% endblock %}

Library/library/templates/library/detail_book.html
{% extends 'base.html' %}
{% block content %}
      <div class="content">
        <div class="book_title">
          <h2> {{ Book.title }} </h2>
        </div>
        <div class="certain_book">
            <div class="book_image">
              <img height="320px" width="200px" src="{{ Book.poster.url }}">
            </div>
            <div class="book_content">
              <h4> Содержание: </h4>
              <p>
                {{ Book.content }}
              </p>
            </div>
            <div class="book_author">
              <h3> Автор: </h3>
              <p>{{ Book.author.name }} {{ Book.author.surname }}</p>
            </div>
            <div class="download_book">
              <h4><a href="{{ Book.main_file.url }}" download="{{ Book.title }}"> Download here</a></h4>
            </div>
        </div>

        <div class="comments">
          <h2> Комментарии </h2>
            {% if Comments %}
                {% for comment in Comments %}
                    <p><b>{{ comment.user_name.username }}:</b> {{ comment.pub_date }} </p>
                    <div class=pub_date><p> {{ comment.comment_body}} </p></div>
                {% endfor %}
            {% else %}
                <p>Прокомментируйте книгу первым.</p>
            {% endif %}
          {% if User.username %}
              <form method="post">
                  {% csrf_token %}
                <center><h3>Оставьте комментарий</h3></center>
                <textarea name=comment maxlength="255"></textarea>
                <center><input class="submit_comment_button" type="submit" value="Send"></center>
              </form>
          {% else %}
            <center><h3>Авторизируйтесь, чтоб у вас была возможность оставить комментарий</h3></center>
          {% endif %}
        </div>
      </div>
{% endblock %}

Library/library/templates/library/feedback.html
{% extends 'base.html' %}

{% block content %}
<div class="сontent">
  <form method="post">
    {% csrf_token %}
    <center><h1> Обратная связь </h1>
    {% if not User.username %}
      <p>Как к вам обращаться</p>
      <input type="text" name="name">
      <p>Введите ваш email:</p>
      <input type="text" name="email">
    {% endif %}
    <p>Напишите нам!</p>
    <textarea name="feed"></textarea>
    <input class="submit_comment_button" type="submit" value="Send"></center>

    {% if Success %}
      <div class="success">
        {{ Success }}
      </div>
    {% endif %}

  </form>
</div>
{% endblock %}

Library/library/templates/library/index.html
{% extends 'base.html' %}

{% block content %}
  <center>
        <h1> Welcome to my library app!</h1>
        <p>
          Приветствую, это мой пет-проект в котором использую фреймворк DJango.
          Здесь реализованы аутентификация и авторизация, при регистрации учтена
          валидация вводимых данных, использую стандартные валидаторы джанги.
          Здесь использую PostgreSQL.
        </p>
  </center>
{% endblock %}